/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ButtonIcon: (typeof import("./components/ButtonIcon/index.vue"))["default"]
    NAvatar: (typeof import("naive-ui"))["NAvatar"]
    NButton: (typeof import("naive-ui"))["NButton"]
    NConfigProvider: (typeof import("naive-ui"))["NConfigProvider"]
    NGi: (typeof import("naive-ui"))["NGi"]
    NGrid: (typeof import("naive-ui"))["NGrid"]
    NSpace: (typeof import("naive-ui"))["NSpace"]
    RouterLink: (typeof import("vue-router"))["RouterLink"]
    RouterView: (typeof import("vue-router"))["RouterView"]
  }
}
